# Generated by Django 4.2.5 on 2023-09-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_userformdata_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='wikipedia_link',
            field=models.URLField(blank=True),
        ),
    ]
